// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const String androidApiKey = String.fromEnvironment('FIREBASE_ANDROID_API_KEY');
  static const String iosApiKey = String.fromEnvironment('FIREBASE_IOS_API_KEY');
  static const String webApiKey = String.fromEnvironment('FIREBASE_WEB_API_KEY', defaultValue: String.fromEnvironment('FIREBASE_API_KEY'));
  static const String windowsApiKey = String.fromEnvironment('FIREBASE_WINDOWS_API_KEY', defaultValue: String.fromEnvironment('FIREBASE_API_KEY'));
  static const String macosApiKey = String.fromEnvironment('FIREBASE_MACOS_API_KEY', defaultValue: String.fromEnvironment('FIREBASE_API_KEY'));

  static FirebaseOptions? get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
      case TargetPlatform.iOS:
        // On Android & iOS, returning null allows Firebase.initializeApp() to fetch 
        // configuration directly from native google-services.json / GoogleService-Info.plist
        if (androidApiKey.isNotEmpty || iosApiKey.isNotEmpty) {
          return defaultTargetPlatform == TargetPlatform.android ? android : ios;
        }
        return null;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEOXx7Smw64A35dEnmhP0gfxE8R4ART3I',
    appId: '1:390785055286:android:55fc0d8ad5273a8f563697',
    messagingSenderId: '390785055286',
    projectId: 'city-of-wealth',
    storageBucket: 'city-of-wealth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF1pFGCj1q50QafW9-W21qtzEdkX6_teQ',
    appId: '1:390785055286:ios:baaad76735fba0d5563697',
    messagingSenderId: '390785055286',
    projectId: 'city-of-wealth',
    storageBucket: 'city-of-wealth.firebasestorage.app',
    androidClientId: '390785055286-fgp3j0qc7v1jngu93mqgh9gpgsbnct9c.apps.googleusercontent.com',
    iosClientId: '390785055286-a2cil9gmrlf8s16buln0olh67in4dapn.apps.googleusercontent.com',
    iosBundleId: 'com.example.cityOfWealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0B0lewor0SCE9N_u9rfBIaPIZN5wrADY',
    appId: '1:390785055286:web:61b4d74b0f4404b4563697',
    messagingSenderId: '390785055286',
    projectId: 'city-of-wealth',
    authDomain: 'city-of-wealth.firebaseapp.com',
    storageBucket: 'city-of-wealth.firebasestorage.app',
    measurementId: 'G-2CTK2CH4TD',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0B0lewor0SCE9N_u9rfBIaPIZN5wrADY',
    appId: '1:390785055286:web:61b4d74b0f4404b4563697',
    messagingSenderId: '390785055286',
    projectId: 'city-of-wealth',
    authDomain: 'city-of-wealth.firebaseapp.com',
    storageBucket: 'city-of-wealth.firebasestorage.app',
    measurementId: 'G-2CTK2CH4TD',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF1pFGCj1q50QafW9-W21qtzEdkX6_teQ',
    appId: '1:390785055286:ios:baaad76735fba0d5563697',
    messagingSenderId: '390785055286',
    projectId: 'city-of-wealth',
    storageBucket: 'city-of-wealth.firebasestorage.app',
    androidClientId: '390785055286-fgp3j0qc7v1jngu93mqgh9gpgsbnct9c.apps.googleusercontent.com',
    iosClientId: '390785055286-a2cil9gmrlf8s16buln0olh67in4dapn.apps.googleusercontent.com',
    iosBundleId: 'com.example.cityOfWealth',
  );

}