name: Daily Question Generator

on:
  schedule:
    - cron: '30 18 * * *' # 00:00 IST (UTC+5:30)
  workflow_dispatch: # Enable manual trigger

jobs:
  generate-quiz:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scripts
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug Info
        run: |
          echo "Current working directory: $(pwd)"
          ls -R ..

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Generator Script
        run: node daily_quiz_generator.js
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
